root: true
env:
  node: true
  browser: true
  es6: true
parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/eslint-recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:yml/standard'
overrides:
  - files: '**/*.js'
    rules:
      '@typescript-eslint/no-inferrable-types':
        - 0
      '@typescript-eslint/explicit-function-return-type':
        - 0
rules:
  '@typescript-eslint/no-inferrable-types':
    - 2
  '@typescript-eslint/explicit-function-return-type':
    - 2
  eqeqeq:
    - 2
  camelcase:
    - 2
  no-console:
    - 2
  no-lonely-if:
    - 2
  comma-dangle:
    - 2
    - arrays: never
      objects: always-multiline
      imports: always-multiline
      exports: always-multiline
      functions: never
  indent:
    - 2
    - 2
  object-curly-spacing:
    - 2
    - always
  array-bracket-spacing:
    - 2
    - always
  curly:
    - 2
    - all
  template-curly-spacing:
    - 2
  no-trailing-spaces:
    - 2
  no-spaced-func:
    - 2
  space-before-blocks:
    - 2
  semi:
    - 2
    - never
  object-curly-newline:
    - 2
    - multiline: true
      minProperties: 2
      consistent: true
  object-property-newline:
    - 2
  object-shorthand:
    - 2
  no-param-reassign:
    - 2
    - props: false
  no-extra-parens:
    - 2
  no-return-await:
    - 2
  no-self-compare:
    - 2
  no-template-curly-in-string:
    - 2
  no-throw-literal:
    - 2
  no-undef-init:
    - 2
  no-undefined:
    - 2
  no-underscore-dangle:
    - 2
    - allowAfterThis: true
  no-unmodified-loop-condition:
    - 2
  no-unneeded-ternary:
    - 2
  no-unreachable-loop:
    - 2
  no-unsafe-optional-chaining:
    - 2
  no-unused-expressions:
    - 2
  no-use-before-define:
    - 2
    - functions: false
  no-useless-backreference:
    - 2
  no-useless-call:
    - 2
  no-useless-computed-key:
    - 2
  no-useless-concat:
    - 2
  no-useless-constructor:
    - 2
  no-useless-rename:
    - 2
  no-useless-return:
    - 2
  no-var:
    - 2
  nonblock-statement-body-position:
    - 2
  one-var-declaration-per-line:
    - 2
  prefer-arrow-callback:
    - 2
  prefer-const:
    - 2
  prefer-exponentiation-operator:
    - 2
  prefer-numeric-literals:
    - 2
  prefer-object-spread:
    - 2
  prefer-promise-reject-errors:
    - 2
  prefer-template:
    - 2
  prefer-rest-params:
    - 2
  rest-spread-spacing:
    - 2
  require-atomic-updates:
    - 2
  require-await:
    - 2
