name: Dev Push

on:
  push:
    branches:
      - dev

jobs:
  dev-build:
    uses: cosmicverse/actions/.github/workflows/dev-build.yml@release
    secrets:
      npm_token: ${{ secrets.npm_token }}
  test:
    needs: dev-build
    uses: cosmicverse/actions/.github/workflows/test.yml@release
    secrets:
      npm_token: ${{ secrets.npm_token }}