name: Dev Pull Request

on:
  pull_request:
    branches:
      - dev

jobs:
  lint:
    uses: cosmicverse/actions/.github/workflows/lint.yml@release
    secrets:
      npm_token: ${{ secrets.npm_token }}
  codeql:
    needs: lint
    uses: cosmicverse/actions/.github/workflows/codeql.yml@release
  dev-build:
    needs: codeql
    uses: cosmicverse/actions/.github/workflows/dev-build.yml@release
    secrets:
      npm_token: ${{ secrets.npm_token }}
  test:
    needs: dev-build
    uses: cosmicverse/actions/.github/workflows/test.yml@release
    secrets:
      npm_token: ${{ secrets.npm_token }}